header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    # Leave empty so `header fix` inserts the current year automatically.
    copyright-year: ''
    # Accept headers with 20xx year or 20xx-20yy range.
    pattern: |
      Copyright (20[0-9]{2}|20[0-9]{2}-20[0-9]{2}) Canonical Ltd\.
      See LICENSE file for licensing details\.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
  paths:
    - '**'
  paths-ignore:
    - '.github/**'
    - '**/.gitkeep'
    - '**/*.cfg'
    - '**/*.conf'
    - '**/*.j2'
    - '**/*.json'
    - '**/*.md'
    - '**/*.rule'
    - '**/*.tmpl'
    - '**/*.txt'
    - '**/*.jinja'
    - '.codespellignore'
    - '.dockerignore'
    - '.flake8'
    - '.jujuignore'
    - '.gitignore'
    - '.licenserc.yaml'
    - '.trivyignore'
    - '.woke.yaml'
    - '.woke.yml'
    - 'CODEOWNERS'
    - 'icon.svg'
    - 'LICENSE'
    - 'trivy.yaml'
    - 'lib/**'
    - '**/*.env'
    - 'terraform/**'
    - "uv.lock"
    - "src/*.egg-info/**"

  comment: on-failure
