# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

temporal-worker-k8s:
  host: "temporal-k8s:7233"
  queue: "test-queue"
  namespace: "default"
  workflows-file-name: "python_samples-1.1.0-py3-none-any.whl"
  supported-workflows: "all"
  supported-activities: "all"
