# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about testing at: https://juju.is/docs/sdk/testing

"""Unit test literals."""

CONTAINER_NAME = "temporal-worker"
CONFIG = {
    "log-level": "debug",
    "host": "test-host",
    "namespace": "test-namespace",
    "queue": "test-queue",
    "sentry-dsn": "",
    "sentry-release": "",
    "sentry-environment": "",
    "encryption-key": "",
    "auth-provider": "candid",
    "tls-root-cas": "",
    "candid-url": "test-url",
    "candid-username": "test-username",
    "candid-public-key": "test-public-key",
    "candid-private-key": "test-private-key",
    "oidc-auth-type": "",
    "oidc-project-id": "",
    "oidc-private-key-id": "",
    "oidc-private-key": "",
    "oidc-client-email": "",
    "oidc-client-id": "",
    "oidc-auth-uri": "",
    "oidc-token-uri": "",
    "oidc-auth-cert-url": "",
    "oidc-client-cert-url": "",
}

VAULT_CONFIG = {
    "vault_address": "127.0.0.1:8081",
    "vault_ca_certificate_bytes": "abcd",
    "vault_mount": "temporal-worker-k8s",
    "vault_role_id": "111",
    "vault_role_secret_id": "222",
    "vault_cert_path": "/vault/cert.pem",
}

DATABASE_CONFIG = {
    "TEMPORAL_DB_HOST": "myhost",
    "TEMPORAL_DB_PORT": "5432",
    "TEMPORAL_DB_USER": "jean-luc",
    "TEMPORAL_DB_PASSWORD": "inner-light",
    "TEMPORAL_DB_TLS": "True",
}

WANT_ENV = {
    "TEMPORAL_AUTH_PROVIDER": "candid",
    "TEMPORAL_CANDID_PRIVATE_KEY": "test-private-key",
    "TEMPORAL_CANDID_PUBLIC_KEY": "test-public-key",
    "TEMPORAL_CANDID_URL": "test-url",
    "TEMPORAL_CANDID_USERNAME": "test-username",
    "TEMPORAL_DB_NAME": "",
    "TEMPORAL_ENCRYPTION_KEY": "",
    "TEMPORAL_HOST": "test-host",
    "TEMPORAL_LOG_LEVEL": "debug",
    "TEMPORAL_NAMESPACE": "test-namespace",
    "TEMPORAL_PROMETHEUS_PORT": 9000,
    "TEMPORAL_OIDC_AUTH_CERT_URL": "",
    "TEMPORAL_OIDC_AUTH_TYPE": "",
    "TEMPORAL_OIDC_AUTH_URI": "",
    "TEMPORAL_OIDC_CLIENT_CERT_URL": "",
    "TEMPORAL_OIDC_CLIENT_EMAIL": "",
    "TEMPORAL_OIDC_CLIENT_ID": "",
    "TEMPORAL_OIDC_PRIVATE_KEY": "",
    "TEMPORAL_OIDC_PRIVATE_KEY_ID": "",
    "TEMPORAL_OIDC_PROJECT_ID": "",
    "TEMPORAL_OIDC_TOKEN_URI": "",
    "TEMPORAL_QUEUE": "test-queue",
    "TEMPORAL_SENTRY_DSN": "",
    "TEMPORAL_SENTRY_ENVIRONMENT": "",
    "TEMPORAL_SENTRY_RELEASE": "",
    "TEMPORAL_SENTRY_SAMPLE_RATE": 1.0,
    "TEMPORAL_SENTRY_REDACT_PARAMS": False,
    "TEMPORAL_TLS_ROOT_CAS": "",
    # The below are kept for backwards-compatibility
    "TWC_AUTH_PROVIDER": "candid",
    "TWC_CANDID_PRIVATE_KEY": "test-private-key",
    "TWC_CANDID_PUBLIC_KEY": "test-public-key",
    "TWC_CANDID_URL": "test-url",
    "TWC_CANDID_USERNAME": "test-username",
    "TWC_DB_NAME": "",
    "TWC_ENCRYPTION_KEY": "",
    "TWC_HOST": "test-host",
    "TWC_LOG_LEVEL": "debug",
    "TWC_NAMESPACE": "test-namespace",
    "TWC_PROMETHEUS_PORT": 9000,
    "TWC_OIDC_AUTH_CERT_URL": "",
    "TWC_OIDC_AUTH_TYPE": "",
    "TWC_OIDC_AUTH_URI": "",
    "TWC_OIDC_CLIENT_CERT_URL": "",
    "TWC_OIDC_CLIENT_EMAIL": "",
    "TWC_OIDC_CLIENT_ID": "",
    "TWC_OIDC_PRIVATE_KEY": "",
    "TWC_OIDC_PRIVATE_KEY_ID": "",
    "TWC_OIDC_PROJECT_ID": "",
    "TWC_OIDC_TOKEN_URI": "",
    "TWC_QUEUE": "test-queue",
    "TWC_SENTRY_DSN": "",
    "TWC_SENTRY_ENVIRONMENT": "",
    "TWC_SENTRY_RELEASE": "",
    "TWC_SENTRY_SAMPLE_RATE": 1.0,
    "TWC_SENTRY_REDACT_PARAMS": False,
    "TWC_TLS_ROOT_CAS": "",
}
