name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - 2.0/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - 2.0/stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
      # Pin the base explicitly
      base-name: ubuntu
      base-channel: "24.04"
      base-architecture: amd64
    secrets: inherit
