name: Terraform checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-terraform-checks:
    name: PR Terraform checks
    uses: canonical/workflows-team/.github/workflows/terraform.yaml@feature/terraform_workflows
